### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by key2market** [prahladyeri/K2M#3]
Please remove the colors and bubbles on the left side for Data Sources, Dimension, Metrics and Filter. Let's have them in plain simple blue lettering.

**Comment by prahladyeri** [comment]
@key2market This is fixed in the latest commit. Download the latest master zip and test:

https://github.com/prahladyeri/K2M/archive/master.zip

**Comment by key2market** [comment]
I still see colors, borders and all other fancy stuff as per attached screenshots.

When selecting a table, can we move the radio button before the text so they are properly aligned and have a space between the button and the text? Can we please remove coloring?

Why do measures have a checkbox? Could we remove that and have them look at feel exactly like dimensions?

![screen shot 2015-12-30 at 8 52 57 am](https://cloud.githubusercontent.com/assets/16460237/12047859/d6edbb30-aed2-11e5-9906-a46408f2a4f3.png)
![screen shot 2015-12-30 at 8 52 17 am](https://cloud.githubusercontent.com/assets/16460237/12047858/d6ecfe48-aed2-11e5-892c-4f261ba0e600.png)

**Comment by prahladyeri** [comment]
> I still see colors, borders and all other fancy stuff as per attached screenshots.

OK, I'll remove that. I thought you might like a monochrome background since it is devoid of proper colors like red, green, etc. 

> Why do measures have a checkbox?

Once you mark a checkbox, that `measure` will be added to the chart. But this is only temporary until I'm done with drag-drop. Once I develop the drag-drop, I'll remove checkbox and instead make another box where you can drag the needed measures.

**Comment by key2market** [comment]
Thanks Prahlad, for now, I would like to keep it as plain as possible and focus on functionality first. :) If all goes well, I might get a designer to do color arrangement etc. so any investment into the look will be wasted.

**Comment by prahladyeri** [comment]
@key2market This is fixed in the latest commit. Download the latest master zip and test:

https://github.com/prahladyeri/K2M/archive/master.zip

**Comment by key2market** [comment]
Not done yet. I had asked above "When selecting a table, can we move the radio button before the text so they are properly aligned and have a space between the button and the text?" I do not see the space

**Comment by prahladyeri** [comment]
Added the space :+1:  Download latest master branch and test.

**Comment by prahladyeri** [comment]
Hey Kirill, you can test this now. Here is how the new radio buttons look:

![selecttable_radio_buttons](https://cloud.githubusercontent.com/assets/5732256/12070496/255e7170-b09e-11e5-9327-122e87cb14e1.png)

Let me know if this is what you wanted.

**Comment by key2market** [comment]
Looks good.
